project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .

preserve_hierarchy: true

files:
  - source: /en/*.json
    translation: /%locale%/%original_file_name%
    type: i18next_json
